// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cloud_logic_custom": [
        {
            "name": "emberAPI",
            "endpoint": "https://58khkd4huf.execute-api.us-east-2.amazonaws.com/ember",
            "region": "us-east-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-2:7644e7a1-f4ce-46d9-8629-cb07894623b6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_apdI1eUfZ",
    "aws_user_pools_web_client_id": "2t4v7vuif239ejbveijb072f41",
    "oauth": {}
};


export default awsmobile;
